### ISSUE TITLE
Create diagrams

### ISSUE THREAD

**Issue by Sannazak** [DIT113-V22/group-14#108]
Create diagrams to provide a better understanding of our project.

Acceptance criteria, at least 2 out of 5. 

- [ ] Journey map
- [ ] Use case diagram
- [ ] Context diagram
- [x] Component Diagram
- [x] Class Diagram

**Comment by EllaGab09** [comment]
Link to diagrams https://github.com/DIT113-V22/group-14/wiki/Diagrams

**Comment by PatyMarklund** [comment]
Link to the third diagram: https://user-images.githubusercontent.com/86784777/170744818-95c752b9-293d-474f-9c00-53030306883b.png
