### ISSUE TITLE
GUI mockup

### ISSUE THREAD

**Issue by harring** [DIT113-V22/group-14#12]
## User story
As a user I want to be able to decide what should be in the user application so a development of the UI can be made successfully with the features driving, plant status, driving speed, camera feed. 

## Acceptance criteria:
- [x] Create a GUI mockup with the features specified.

**Comment by Sannazak** [comment]
Created a basic GUI, follow the link for the slide: https://docs.google.com/presentation/d/1SrHGW4eAhuL-4G-y3P0KRYM-HpgYRK7OkYgQqJxowog/edit#slide=id.g1244cf1277c_1_10
