### ISSUE TITLE
Finalize features specification

### ISSUE THREAD

**Issue by Sannazak** [DIT113-V22/group-14#25]
(https://canvas.gu.se/courses/56718/assignments/154139)
Sat, 28 May 2022, 23.59

- [x] Provide a link to your milestones and make sure that all of them contain links to your features on the wiki
- [x] Finalize the wiki pages containing the features specification and the corresponding requirements.

Some ideas on how to improve existing requirements documentation and overall process structure:
- [x] Make sure that all stories (GitHub issues) are linked to Milestones and it is clear which commit(s) solve them
- [x] Enrich requirements with more details, examples and usage scenarios

**Comment by EllaGab09** [comment]
Updated each milestone accordingly 
https://github.com/DIT113-V22/group-14/milestones
