### ISSUE TITLE
Car brake commands

### ISSUE THREAD

**Issue by harring** [DIT113-V22/group-14#8]
## User story
As a user I want the car to be able to stop completely on command so that I can assess the plants.

## Acceptance criteria:
- [x] The car will stop completely when receiving the command to stop.

**Comment by harring** [comment]
Solved by going another route for how we will controll the car, this is no longer needed.

**Comment by DragosIsar** [comment]
This is accomplished through the broker and android app connection. The car stops completely upon pressing the "stop" button in the android app.
